replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: alpine

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP   # Podés cambiar a NodePort o LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
